version: '3.9'

services:
    postgres:
        container_name: api-money-plus-postgres
        image: postgres:14-alpine
        restart: on-failure
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: money_plus_db
            POSTGRES_HOST_AUTH_METHOD: scram-sha-256
            POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
